version: "3.3"

services:
    web:
        container_name: lastfmtube
        build:
            context: .
            dockerfile: lastfmtube.Dockerfile
        ports:
            - "80:80"
        volumes:
            - /var/www/html/vendor
            - .:/var/www/html
        restart: always